services:
  Dbp\Relay\CoreBundle\Serializer\ApiErrorNormalizer:
    autowire: true
    autoconfigure: false
    tags: [{'name' : 'serializer.normalizer', priority: '-700'}]

  Dbp\Relay\CoreBundle\Logging\LoggingProcessor:
    autowire: true
    autoconfigure: true
    tags:
      - { name: monolog.processor }

  Dbp\Relay\CoreBundle\Cron\CronCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Cron\CronJobs\:
    resource: '../../Cron/CronJobs'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Swagger\OpenApiDecorator:
    decorates: 'api_platform.openapi.factory'
    autowire: true
    autoconfigure: false

  Dbp\Relay\CoreBundle\Queue\TransportFactoryDecorator:
    decorates: 'messenger.transport_factory'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\WorkCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\RestartCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\TestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\TestHandler:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\HealthCheck\HealthCheckCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\HealthCheck\Checks\:
    resource: '../../HealthCheck/Checks'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Auth\ProxyAuthenticator:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\LocalData\LocalDataAwareEventDispatcher:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\LocalData\LocalDataAwareEvent:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Routing\RoutingLoader:
    tags: ['routing.loader']
    autowire: true
    autoconfigure: true
    arguments:
      $env: ~

  Dbp\Relay\CoreBundle\Pagination\Pagination:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Authorization\Authorization:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Authorization\AuthorizationAwareService:
    autowire: true
    autoconfigure: true