services:
  DBP\API\CoreBundle\Service\GuzzleLogger:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\AuditLogger:
    public: false
    autowire: true
    autoconfigure: true