services:
  Dbp\Relay\CoreBundle\TestUtils\Internal\TestAuthenticator:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\CoreBundle\TestUtils\TestUserAttributeProviderProvider:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface:
    '@Dbp\Relay\CoreBundle\TestUtils\Internal\TestAuthenticator'

  Dbp\Relay\CoreBundle\User\UserAttributeProviderProviderInterface:
    '@Dbp\Relay\CoreBundle\TestUtils\TestUserAttributeProviderProvider'

  Dbp\Relay\CoreBundle\Doctrine\MigrationFactoryDecorator: null
