services:
  Dbp\Relay\CoreBundle\TestUtils\TestUserSession:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\CoreBundle\TestUtils\TestAuthenticator:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface:
    '@Dbp\Relay\CoreBundle\TestUtils\TestAuthenticator'

  Dbp\Relay\CoreBundle\API\UserSessionInterface:
    '@Dbp\Relay\CoreBundle\TestUtils\TestUserSession'
