services:
  DBP\API\CoreBundle\Serializer\ApiErrorNormalizer:
    autowire: true
    autoconfigure: false
    tags: [{'name' : 'serializer.normalizer', priority: '-700'}]

  DBP\API\CoreBundle\Service\LoggingProcessor:
    autowire: true
    autoconfigure: true
    tags:
      - { name: monolog.processor }

  DBP\API\CoreBundle\Command\CronCommand:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\DummyUserSession:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\API\UserSessionInterface:
    '@DBP\API\CoreBundle\Service\DummyUserSession'

  DBP\API\CoreBundle\Keycloak\KeycloakBearerAuthenticator:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProvider:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProviderInterface:
    '@DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProvider'

  DBP\API\CoreBundle\Swagger\OpenApiDecorator:
    decorates: 'api_platform.openapi.factory'
    autowire: true
    autoconfigure: false

  # This alias exist so we can replace the service during tests
  test.UserProviderInterface:
    alias: 'DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProviderInterface'
    public: true
