services:
  Dbp\Relay\CoreBundle\Serializer\ApiErrorNormalizer:
    autowire: true
    autoconfigure: false
    tags: [{'name' : 'serializer.normalizer', priority: '-700'}]

  Dbp\Relay\CoreBundle\Service\LoggingProcessor:
    autowire: true
    autoconfigure: true
    tags:
      - { name: monolog.processor }

  Dbp\Relay\CoreBundle\Command\CronCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Swagger\OpenApiDecorator:
    decorates: 'api_platform.openapi.factory'
    autowire: true
    autoconfigure: false
