services:
  DBP\API\CoreBundle\Serializer\ApiErrorNormalizer:
    autowire: true
    autoconfigure: false
    tags: [{'name' : 'serializer.normalizer', priority: '-700'}]

  DBP\API\CoreBundle\Controller\:
    resource: '../../Controller'
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\LoggingProcessor:
    autowire: true
    autoconfigure: true
    tags:
      - { name: monolog.processor }

  DBP\API\CoreBundle\Command\CronCommand:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\OrganizationProviderInterface:
    '@DBP\API\CoreBundle\Service\DummyOrganizationProvider'

  DBP\API\CoreBundle\Service\DummyOrganizationProvider:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\DummyPersonProvider:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\PersonProviderInterface:
    '@DBP\API\CoreBundle\Service\DummyPersonProvider'

  DBP\API\CoreBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProvider:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Keycloak\KeycloakBearerAuthenticator:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Serializer\PersonAttributeNormalizer:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Swagger\SwaggerDecorator:
    decorates: 'api_platform.swagger.normalizer.api_gateway'
    autowire: true
    autoconfigure: false

  DBP\API\CoreBundle\Swagger\OpenApiDecorator:
    decorates: 'api_platform.openapi.factory'
    autowire: true
    autoconfigure: false

  # This alias exist so we can replace the service during tests
  test.App\Security\User\KeycloakBearerUserProvider:
    alias: 'DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProvider'
    public: true

  # This alias exist so we can replace the service during tests
  test.App\Service\PersonProviderInterface:
    alias: 'DBP\API\CoreBundle\Service\PersonProviderInterface'
    public: true
