services:
  Dbp\Relay\CoreBundle\Serializer\ApiErrorNormalizer:
    autowire: true
    autoconfigure: false
    tags: [{'name' : 'serializer.normalizer', priority: '-700'}]

  Dbp\Relay\CoreBundle\Logging\LoggingProcessor:
    autowire: true
    autoconfigure: true
    tags:
      - { name: monolog.processor }

  Dbp\Relay\CoreBundle\Cron\CronCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Cron\CronListCommand:
    autowire: true
    autoconfigure: true

  dbp.relay.core.cache.cron:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 0 }

  Dbp\Relay\CoreBundle\Cron\CronManager:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.core.cache.cron' ]

  Dbp\Relay\CoreBundle\Cron\CronJobs\:
    resource: '../../Cron/CronJobs'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Swagger\OpenApiDecorator:
    decorates: 'api_platform.openapi.factory'
    autowire: true
    autoconfigure: false

  Dbp\Relay\CoreBundle\Queue\TransportFactoryDecorator:
    decorates: 'messenger.transport_factory'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\WorkCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\RestartCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\TestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Queue\TestHandler:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\HealthCheck\HealthCheckCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\HealthCheck\Checks\:
    resource: '../../HealthCheck/Checks'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Auth\ProxyAuthenticator:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Auth\UserSession:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\API\UserSessionInterface:
    '@Dbp\Relay\CoreBundle\Auth\UserSession'

  Dbp\Relay\CoreBundle\LocalData\LocalDataAwareEventDispatcher:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\LocalData\LocalDataAwareEvent:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Routing\RoutingLoader:
    tags: ['routing.loader']
    autowire: true
    autoconfigure: true
    arguments:
      $env: ~

  Dbp\Relay\CoreBundle\Pagination\Pagination:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\DB\MigrateCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Helpers\Locale:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Authorization\DebugCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Authorization\EventSubscriber\ProxyDataEventSubscriber:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\Locale\Locale:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\DataProvider\AbstractDataProvider:
    abstract:  true
    calls:
      - setLocale: ['@locale']

  Dbp\Relay\CoreBundle\Internal\CacheWarmer:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreBundle\User\UserAttributeProviderProvider:
    autowire: true
    autoconfigure: true
    arguments: [ !tagged user.user_attribute_provider ]

  Dbp\Relay\CoreBundle\User\UserAttributeMuxer:
    autowire: true
    autoconfigure: true