services:
  DBP\API\CoreBundle\Service\GuzzleLogger:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\AuditLogger:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\DataProvider\OrganizationDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\DataProvider\PersonItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\DataProvider\PersonCollectionDataProvider:
    tags: ['api_platform.collection_data_provider']
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Keycloak\KeycloakBearerUserProvider:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Keycloak\KeycloakBearerAuthenticator:
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\PersonProviderInterface:
    factory: ['DBP\API\CoreBundle\Service\PersonProviderFactory', 'createPersonProvider']
    autowire: true
    autoconfigure: true

  DBP\API\CoreBundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

